/**
 * NUNJA Pad and Strings v0.1
 * pads_strings.scd
                             ___
                     /======/
            ____    //      \___       ,/
             | \\  //           :,   ./
     |_______|__|_//            ;:; /
    _L_____________\o           ;;;/
____(CCCCCCCCCCCCCC)____________-/____________________


 */

~osPath = "/Users/nunja/Documents/AudioLib/supercollider/pad/*";
~PadAndStrings = ();
//~PadAndStrings

